version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
    ports:
      - "1433:1433"
    networks:
      - test-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    networks:
      - test-network
    ports:
      - "5000:80"

networks:
  test-network:
    driver: bridge

volumes:
  sqlserver-data:
